# Generated by Django 3.2.7 on 2021-10-04 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_number',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True),
        ),
    ]
