# Generated by Django 3.2.7 on 2021-10-04 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_alter_business_staffs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='staffs',
        ),
        migrations.AlterField(
            model_name='businessstaff',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffs', to='business.business'),
        ),
    ]
