# Generated by Django 3.2.7 on 2021-10-05 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0004_auto_20211005_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstaff',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_staffs', to='business.business'),
        ),
    ]
