# Generated by Django 3.2.7 on 2021-10-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_alter_businessstaff_business'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessstaff',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
