# Generated by Django 3.2.7 on 2021-10-05 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0006_businessstaff_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessstaff',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
